[program:odr-encoderManager]
command=python3 run.py -c /home/odr/.config/odr/odr-encodermanager.json
directory=/home/odr/odr-encodermanager/
autostart=true
autorestart=true
priority=10
user=odr
group=odr
redirect_stderr=true
stdout_logfile=/var/log/supervisor/odr-encodermanager.log
